### ISSUE TITLE
Error when pip installing elasticdeform

### ISSUE THREAD

**Issue by calvinthommek** [kapoorlab/SegmentationTerminator#1]
Hey,
when trying to pip install elasticdeform this Error Comes up.+

<img width="1155" alt="Unbenannt" src="https://user-images.githubusercontent.com/62650180/78244907-c8e56b80-74e6-11ea-82fb-50bcd5517f6c.PNG">

**Comment by kapoorlab** [comment]
Hi Calvin,

You are missing the C++ compilers that are needed for this and other programs to run. For windows you can install the needed C++ compilers from here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
After installing the C++ compilers/ visual studio you may have to restart your computer for the changes to take affect. 

Let me know if it solves the issue.

Best,
Varun

**Comment by calvinthommek** [comment]
Hi, 
I just downloaded Microsoft Visual Studio 19 and restarted but it doesnt solve the Problem. Same Error occurs. I'm using a MacBook, dont know if that has any effect.

Best, 
Calvin

**Comment by kapoorlab** [comment]
Hi,

If you are using mac you should instead try to install gcc version 8 and 9 by running these two commands:
brew install gcc@8
brew install gcc@9
then open a new terminal and try to pip install elasticdeform. Basically you are missing C++ compilers on your Mac and elasticdeform and stardist need that to perform some openCV operations.
